azure:
  subscription_id : 'XXXXXX'
  resource_group : 'XXXXXX'
  aml_workspace_name : 'XXXXXX'
  project_name : 'ASR-MSDD'
  cluster_aml_id : 'gpu-cluster'
  experiment_name : 'asr-msdd-inference'
  keyvault_name: 'XXXXXX'
  secret_name: 'XXXXXX'
  data_filepath: 'XXXXXX'

preprocessing:
  vad_threshold: 0.7
  min_speech_duration_ms: 250
  min_silence_duration_ms: 100
  speech_pad_ms: 400
  use_onnx_vad: True
  demucs_model: 'htdemucs'

asr:
  model_name: 'openai/whisper-large-v2'
  compute_type: 'float16'
  chunk_length_s: 30
  batch_size: 8

fa:
  model_name: "stt_es_fastconformer_hybrid_large_pc"
  batch_size: 16

diarization:
  event_type: 'telephonic' #could also be 'meeting'
  max_num_speakers: 3

align:
  max_words_in_sentence: 60