azure:
  subscription_id : 'XXXXXX'
  resource_group : 'XXXXXX'
  aml_workspace_name : 'XXXXXX'
  project_name : 'ASR-MSDD'
  computing:
    cpu_cluster_aml_id : 'cpu-cluster'
    gpu_cluster_aml_id : 'gpu-cluster'
  experiment_name : 'asr-msdd-inference'
  data_filepath: 'XXXXXX'

preprocessing:
  vad_threshold: 0.75
  min_speech_duration_ms: 250
  min_silence_duration_ms: 100
  speech_pad_ms: 400
  use_onnx_vad: True
  demucs_model: 'htdemucs'

asr:
  model_name: 'large-v2'
  num_workers: 4
  beam_size: 5
  word_level_timestamps: true
  condition_on_previous_text: true
  language_code: 'es'
  compute_type: 'float16'

fa:
  model_name: "stt_es_fastconformer_hybrid_large_pc"
  batch_size: 16

diarization:
  event_type: 'telephonic' #could also be 'meeting'
  max_num_speakers: 3

align:
  max_words_in_sentence: 60

job:
  instance_count: 2
  max_concurrency_per_instance: 1
  mini_batch_size: "1"
  mini_batch_error_threshold: 1
  error_threshold: 1
  max_retries: 2
  timeout: 3600
  allowed_failed_percent: 0
  progress_update_timeout: 60000
  task_overhead_timeout: 3600
  first_task_creation_timeout: 60000
  resource_monitor_interval: 0