name: read_data_conda_env
channels:
  - defaults
dependencies:
  - python=3.7.11
  - pip=20.0
  - pip:
    - azureml-defaults==1.47.0
    - azure-identity==1.12.0
    - azure-storage-blob==12.13.0
    - protobuf==3.20.0
    - pandas==1.3.5
    - pyyaml==5.4.1
    - fire==0.4.0