azure:
  subscription_id : 'XXXXXX'
  resource_group : 'XXXXXX'
  aml_workspace_name : 'XXXXXX'
endpoint:
  name: 'stt-service'
  description: 'API to run a STT batch inference AzureML pipeline.'
deployment:
  name:
  description:
  default_compute: 'XXXXXX'