# Base image
FROM mcr.microsoft.com/azureml/curated/python-sdk-v2:10

# Install dependencies
RUN pip install 'azure-storage-blob==12.13.0' \
                'pandas==2.0.2' \
                'numpy==1.24.3' \
                'protobuf==3.20.0' \
                'pyyaml==5.4.1' \
                'fire==0.4.0'