azure:
  subscription_id : 'XXXXXX'
  resource_group : 'XXXXXX'
  aml_workspace_name : 'XXXXXX'
  project_name : 'ASR-MSDD'
  computing:
    cpu_cluster_aml_id : 'XXXXXX'
    gpu_cluster_aml_id : 'XXXXXX'
  experiment_name : 'asr-msdd-inference'
data:
  storage_id : 'XXXXXX'
  container_id : 'XXXXXX'
  regex_pattern : '(.*?)\.wav'
inference:
  whisper_model_name: 'large-v2'
  vad_threshold: 0.35
  no_speech_threshold: 0.5
  language_code: 'es' # en, fr, pt, ch,...
  event_type: 'telephonic'