# Base image
FROM mcr.microsoft.com/azureml/curated/python-sdk-v2:10

# Install dependencies
RUN pip install 'protobuf==3.20.0' \
                'pyyaml==5.4.1' \
                'azureml-inference-server-http==1.0.0' \
                'fire==0.5.0' 